export const images = {
  '콜_고로케.jpg': require('../src/assets/product-images/콜_고로케.jpg'),
  '콜_뉴욕치즈타르트.jpg': require('../src/assets/product-images/콜_뉴욕치즈타르트.jpg'),
  '콜_단팥빵.jpg': require('../src/assets/product-images/콜_단팥빵.jpg'),
  '콜_단호박바게트.jpg': require('../src/assets/product-images/콜_단호박바게트.jpg'),
  '콜_마늘스틱.jpg': require('../src/assets/product-images/콜_마늘스틱.jpg'),
  '콜_먹물양파빵.jpg': require('../src/assets/product-images/콜_먹물양파빵.jpg'),
  '콜_먹물치즈바게트.jpg': require('../src/assets/product-images/콜_먹물치즈바게트.jpg'),
  '콜_모닝빵.jpg': require('../src/assets/product-images/콜_모닝빵.jpg'),
  '콜_바게트.jpg': require('../src/assets/product-images/콜_바게트.jpg'),
  '콜_부추빵.jpg': require('../src/assets/product-images/콜_부추빵.jpg'),
  '콜_앙버터.jpg': require('../src/assets/product-images/콜_앙버터.jpg'),
  '콜_엘리게이터.jpg': require('../src/assets/product-images/콜_엘리게이터.jpg'),
  '콜_우유바구니.jpg': require('../src/assets/product-images/콜_우유바구니.jpg'),
  '콜_크루아상.jpg': require('../src/assets/product-images/콜_크루아상.jpg'),
  '콜_호두파이.jpg': require('../src/assets/product-images/콜_호두파이.jpg'),
  '콜_흑임자츄러스.jpg': require('../src/assets/product-images/콜_흑임자휴러스.jpg'),
  '콜_소보로.jpg': require('../src/assets/product-images/콜_소보로.jpg'),
};
